### PR TITLE
Add Run/Install instructions + AUR Package

### PR DESCRIPTION
**Pull request by aakashhemadri**
Signed-off-by: Aakash Hemadri <aakashhemadri123@gmail.com>

### CODE REVIEW

**Comment by aakashhemadri** [comment]
@pixeltris I wanted to support this port on AUR I thought it'd be nice if I added the information to the README. Open to changes :)

**Comment by pixeltris** [comment]
The README needs improvements in general as mentioned by a few people that instructions aren't super clear.

I'm going to hold off on merging this and look at overhauling the README some-when soon, which would include the info about your package.

**Comment by konsumer** [comment]
I missed this PR, and did one for Linux, too (#162) Sorry. Feel free to remove it, or merge them all together however you want.

**Comment by aakashhemadri** [comment]
@konsumer The udev rule section is helpful! Thanks for the nice contribution. @pixeltris Would be great if we can update the README, If possible can you express your expectations in the form of sub headings. I don't mind filling in the details.

**Comment by konsumer** [comment]
I missed an  `s` on the rules filename, but added that to the other PR. should be `/etc/udev/rules.d/gk6x.rules`

**Comment by pixeltris** [comment]
@aakashhemadri I've gone ahead and made the README changes I mentioned I was going to make. I've included your AUR package under the `System requirements / compilation` section. It's currently under a drop down as the README is a little noisy with the more verbose instruction. I hope this suffices.

**Pull request closed without merging**
